<script>
	import Header from '../blocks/Header.svelte'
	import PageHeader from '../blocks/PageHeader.svelte'
	import BasicContent from '../blocks/BasicContent.svelte'
	import Cta from '../blocks/Cta.svelte'
	import Footer from '../blocks/Footer.svelte'
</script>

	<Header logo={{"type":"text","text":"SaaSify","image":{"url":"","alt":""}}} nav_links={[{"link":{"label":"Features","url":"#features"}},{"link":{"label":"Pricing","url":"#pricing"}},{"link":{"label":"About","url":"/about"}},{"link":{"label":"Contact","url":"/contact"}}]} header_cta={{"label":"Get Started","url":"#signup"}} />
	<PageHeader title={"About Us"} subtitle={"We're on a mission to help teams ship faster."} />
	<BasicContent content={"<h2>Our Story</h2>\n<p>SaaSify was founded in 2024 with a simple mission: make it easier for teams to build and ship great software. We believe that developers should spend their time solving problems, not wrestling with infrastructure.</p>\n\n<h2>Our Mission</h2>\n<p>We're building the all-in-one platform that helps your team build, deploy, and scale applications without the complexity. From startups to enterprises, we're trusted by teams who want to move fast without breaking things.</p>\n\n<h2>Our Values</h2>\n<ul>\n  <li><strong>Ship fast, iterate faster</strong> - We believe in rapid iteration and continuous improvement.</li>\n  <li><strong>Developer experience first</strong> - Every feature we build is designed with developers in mind.</li>\n  <li><strong>Transparency</strong> - We're open about our roadmap, pricing, and how we operate.</li>\n  <li><strong>Customer obsession</strong> - Your success is our success.</li>\n</ul>\n"} />
	<Cta title={"Join our journey"} subtitle={"See why thousands of teams trust SaaSify."} primary_cta={{"label":"Start for free","url":"/#signup"}} secondary_cta={{"label":"Contact us","url":"/contact"}} />
	<Footer logo={{"type":"text","text":"SaaSify","image":{"url":"","alt":""}}} tagline={"The all-in-one platform that helps your team build, deploy, and scale applications without the complexity."} social_links={[{"platform":"twitter","url":"https://twitter.com/saasify"},{"platform":"linkedin","url":"https://linkedin.com/company/saasify"},{"platform":"github","url":"https://github.com/saasify"}]} footer_link_groups={[{"title":"Product","links":[{"link":{"label":"Features","url":"#features"}},{"link":{"label":"Pricing","url":"#pricing"}},{"link":{"label":"Changelog","url":"/changelog"}}]},{"title":"Company","links":[{"link":{"label":"About","url":"/about"}},{"link":{"label":"Blog","url":"/blog"}},{"link":{"label":"Contact","url":"/contact"}}]},{"title":"Legal","links":[{"link":{"label":"Privacy","url":"/privacy"}},{"link":{"label":"Terms","url":"/terms"}}]}]} copyright={"© 2026 SaaSify. All rights reserved."} />
