<script>
	import Header from '../blocks/Header.svelte'
	import ArticleHeader from '../blocks/ArticleHeader.svelte'
	import BasicContent from '../blocks/BasicContent.svelte'
	import Cta from '../blocks/Cta.svelte'
	import Footer from '../blocks/Footer.svelte'
</script>

	<Header logo={{"type":"text","text":"SaaSify","image":{"url":"","alt":""}}} nav_links={[{"link":{"label":"Features","url":"#features"}},{"link":{"label":"Pricing","url":"#pricing"}},{"link":{"label":"About","url":"/about"}},{"link":{"label":"Contact","url":"/contact"}}]} header_cta={{"label":"Get Started","url":"#signup"}} />
	<ArticleHeader title={"How We Stay Productive as a Fully Remote Team"} excerpt={"Our playbook for building a high-performing remote team across multiple time zones."} author={"Jordan Taylor"} date={"February 20, 2026"} image={{"url":"https://images.unsplash.com/photo-1587560699334-cc4ff634909a?w=900&q=80&auto=format&fit=crop","alt":"Remote work setup"}} />
	<BasicContent content={"<p><em>By Jordan Taylor, Head of Product</em></p>\n\n<p>SaaSify has been fully remote since day one. With team members across 8 time zones, we've had to be intentional about how we work together. Here's what's working for us.</p>\n\n<h2>Async-First Communication</h2>\n<p>Real-time communication is expensive—it requires everyone to be available at the same time. We default to async communication for everything that doesn't require immediate discussion.</p>\n<p>This means writing things down, using Loom for complex explanations, and being patient with response times. The result? Better documentation, more thoughtful responses, and fewer interruptions.</p>\n\n<h2>Overlap Hours, Not Full Days</h2>\n<p>We require everyone to be available for 4 \"overlap hours\" each day. This gives us time for real-time collaboration while respecting that people have different schedules and lives.</p>\n<p>During overlap hours, we handle meetings, pair programming, and anything that benefits from synchronous communication.</p>\n\n<h2>Write Everything Down</h2>\n<p>In an office, you can tap someone on the shoulder to ask a question. Remote teams don't have that luxury. We document everything:</p>\n<ul>\n  <li>Meeting notes with decisions and action items</li>\n  <li>Project proposals before starting work</li>\n  <li>Postmortems after incidents</li>\n  <li>Onboarding guides for new team members</li>\n</ul>\n<p>If it's not written down, it didn't happen.</p>\n\n<h2>Intentional Social Time</h2>\n<p>Remote work can be isolating. We've created opportunities for informal connection: virtual coffee chats, a #random Slack channel, and quarterly in-person meetups.</p>\n<p>These moments of connection aren't fluff—they build the trust that makes async work possible.</p>\n\n<h2>Results Over Hours</h2>\n<p>We measure output, not input. No one tracks hours or monitors screens. We trust our team to do their best work on their own schedule.</p>\n<p>This trust is earned through clear goals, regular check-ins, and transparency about progress.</p>\n\n<h2>Tools That Work</h2>\n<p>Our remote stack:</p>\n<ul>\n  <li><strong>Slack</strong> for daily communication</li>\n  <li><strong>Notion</strong> for documentation</li>\n  <li><strong>Linear</strong> for project management</li>\n  <li><strong>Loom</strong> for async video</li>\n  <li><strong>Figma</strong> for design collaboration</li>\n  <li><strong>SaaSify</strong> for... well, everything else!</li>\n</ul>\n\n<h2>It's Not for Everyone</h2>\n<p>Remote work requires discipline, self-motivation, and strong written communication skills. We're upfront about this in our hiring process. Not everyone thrives in this environment, and that's okay.</p>\n"} />
	<Cta title={"Join our remote team"} subtitle={"We're always looking for talented people who thrive in async environments."} primary_cta={{"label":"View open roles","url":"/careers"}} secondary_cta={{"label":"Learn about us","url":"/about"}} />
	<Footer logo={{"type":"text","text":"SaaSify","image":{"url":"","alt":""}}} tagline={"The all-in-one platform that helps your team build, deploy, and scale applications without the complexity."} social_links={[{"platform":"twitter","url":"https://twitter.com/saasify"},{"platform":"linkedin","url":"https://linkedin.com/company/saasify"},{"platform":"github","url":"https://github.com/saasify"}]} footer_link_groups={[{"title":"Product","links":[{"link":{"label":"Features","url":"#features"}},{"link":{"label":"Pricing","url":"#pricing"}},{"link":{"label":"Changelog","url":"/changelog"}}]},{"title":"Company","links":[{"link":{"label":"About","url":"/about"}},{"link":{"label":"Blog","url":"/blog"}},{"link":{"label":"Contact","url":"/contact"}}]},{"title":"Legal","links":[{"link":{"label":"Privacy","url":"/privacy"}},{"link":{"label":"Terms","url":"/terms"}}]}]} copyright={"© 2026 SaaSify. All rights reserved."} />
