<script>
	import Header from '../blocks/Header.svelte'
	import PageHeader from '../blocks/PageHeader.svelte'
	import BlogListing from '../blocks/BlogListing.svelte'
	import Cta from '../blocks/Cta.svelte'
	import Footer from '../blocks/Footer.svelte'
</script>

	<Header logo={{"type":"text","text":"SaaSify","image":{"url":"","alt":""}}} nav_links={[{"link":{"label":"Features","url":"#features"}},{"link":{"label":"Pricing","url":"#pricing"}},{"link":{"label":"About","url":"/about"}},{"link":{"label":"Contact","url":"/contact"}}]} header_cta={{"label":"Get Started","url":"#signup"}} />
	<PageHeader title={"Blog"} subtitle={"Insights, tutorials, and best practices to help you build better products."} />
	<BlogListing posts={[{"title":"API Design Best Practices: What We Learned Building Our Platform","canonical_url":"/blog/api-design-best-practices","featured_image":{"url":"https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80&auto=format&fit=crop","alt":"Code on screen"},"author":"Sam Chen","excerpt":"A deep dive into the API design principles that helped us create a developer-friendly platform.","publish_date":"February 28, 2026","description":"A deep dive into the API design principles that helped us create a developer-friendly platform.","color":"#6366f1","icon":"iconoir:journal-page","_meta":{"name":"API Design Best Practices: What We Learned Building Our Platform","url":"/blog/api-design-best-practices"}},{"title":"How We Stay Productive as a Fully Remote Team","canonical_url":"/blog/remote-team-productivity","featured_image":{"url":"https://images.unsplash.com/photo-1587560699334-cc4ff634909a?w=800&q=80&auto=format&fit=crop","alt":"Remote work setup"},"author":"Jordan Taylor","excerpt":"Our playbook for building a high-performing remote team across multiple time zones.","publish_date":"February 20, 2026","description":"Our playbook for building a high-performing remote team across multiple time zones.","color":"#6366f1","icon":"iconoir:journal-page","_meta":{"name":"How We Stay Productive as a Fully Remote Team","url":"/blog/remote-team-productivity"}},{"title":"5 Lessons We Learned Scaling Our Startup to 10,000 Users","canonical_url":"/blog/scaling-your-startup","featured_image":{"url":"https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80&auto=format&fit=crop","alt":"Team collaboration"},"author":"Alex Rivera","excerpt":"The journey from 0 to 10,000 users taught us invaluable lessons about infrastructure, team dynamics, and customer focus.","publish_date":"March 5, 2026","description":"The journey from 0 to 10,000 users taught us invaluable lessons about infrastructure, team dynamics, and customer focus.","color":"#6366f1","icon":"iconoir:journal-page","_meta":{"name":"5 Lessons We Learned Scaling Our Startup to 10,000 Users","url":"/blog/scaling-your-startup"}}]} />
	<Cta title={"Want more insights?"} subtitle={"Subscribe to our newsletter for weekly tips and updates."} primary_cta={{"label":"Subscribe","url":"#subscribe"}} secondary_cta={{"label":"Follow on Twitter","url":"https://twitter.com"}} />
	<Footer logo={{"type":"text","text":"SaaSify","image":{"url":"","alt":""}}} tagline={"The all-in-one platform that helps your team build, deploy, and scale applications without the complexity."} social_links={[{"platform":"twitter","url":"https://twitter.com/saasify"},{"platform":"linkedin","url":"https://linkedin.com/company/saasify"},{"platform":"github","url":"https://github.com/saasify"}]} footer_link_groups={[{"title":"Product","links":[{"link":{"label":"Features","url":"#features"}},{"link":{"label":"Pricing","url":"#pricing"}},{"link":{"label":"Changelog","url":"/changelog"}}]},{"title":"Company","links":[{"link":{"label":"About","url":"/about"}},{"link":{"label":"Blog","url":"/blog"}},{"link":{"label":"Contact","url":"/contact"}}]},{"title":"Legal","links":[{"link":{"label":"Privacy","url":"/privacy"}},{"link":{"label":"Terms","url":"/terms"}}]}]} copyright={"© 2026 SaaSify. All rights reserved."} />
