<script>
	import Header from '../blocks/Header.svelte'
	import PageHeader from '../blocks/PageHeader.svelte'
	import BasicContent from '../blocks/BasicContent.svelte'
	import Footer from '../blocks/Footer.svelte'
</script>

	<Header logo={{"type":"text","text":"SaaSify","image":{"url":"","alt":""}}} nav_links={[{"link":{"label":"Features","url":"#features"}},{"link":{"label":"Pricing","url":"#pricing"}},{"link":{"label":"About","url":"/about"}},{"link":{"label":"Contact","url":"/contact"}}]} header_cta={{"label":"Get Started","url":"#signup"}} />
	<PageHeader title={"Privacy Policy"} subtitle={"Last updated March 2026"} />
	<BasicContent content={"<h2>Introduction</h2>\n<p>At SaaSify, we take your privacy seriously. This policy describes how we collect, use, and protect your personal information.</p>\n\n<h2>Information We Collect</h2>\n<p>We collect information you provide directly to us, such as when you create an account, use our services, or contact us for support.</p>\n<ul>\n  <li>Account information (name, email, password)</li>\n  <li>Usage data (how you interact with our services)</li>\n  <li>Payment information (processed securely by our payment provider)</li>\n</ul>\n\n<h2>How We Use Your Information</h2>\n<p>We use the information we collect to:</p>\n<ul>\n  <li>Provide, maintain, and improve our services</li>\n  <li>Process transactions and send related information</li>\n  <li>Send you technical notices and support messages</li>\n  <li>Respond to your comments and questions</li>\n</ul>\n\n<h2>Data Security</h2>\n<p>We implement appropriate technical and organizational measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.</p>\n\n<h2>Your Rights</h2>\n<p>You have the right to access, correct, or delete your personal information. Contact us at <a href=\"mailto:privacy@saasify.com\">privacy@saasify.com</a> to exercise these rights.</p>\n\n<h2>Contact Us</h2>\n<p>If you have questions about this privacy policy, please contact us at <a href=\"mailto:privacy@saasify.com\">privacy@saasify.com</a>.</p>\n"} />
	<Footer logo={{"type":"text","text":"SaaSify","image":{"url":"","alt":""}}} tagline={"The all-in-one platform that helps your team build, deploy, and scale applications without the complexity."} social_links={[{"platform":"twitter","url":"https://twitter.com/saasify"},{"platform":"linkedin","url":"https://linkedin.com/company/saasify"},{"platform":"github","url":"https://github.com/saasify"}]} footer_link_groups={[{"title":"Product","links":[{"link":{"label":"Features","url":"#features"}},{"link":{"label":"Pricing","url":"#pricing"}},{"link":{"label":"Changelog","url":"/changelog"}}]},{"title":"Company","links":[{"link":{"label":"About","url":"/about"}},{"link":{"label":"Blog","url":"/blog"}},{"link":{"label":"Contact","url":"/contact"}}]},{"title":"Legal","links":[{"link":{"label":"Privacy","url":"/privacy"}},{"link":{"label":"Terms","url":"/terms"}}]}]} copyright={"© 2026 SaaSify. All rights reserved."} />
