<script>
	import Header from '../blocks/Header.svelte'
	import PageHeader from '../blocks/PageHeader.svelte'
	import BasicContent from '../blocks/BasicContent.svelte'
	import Footer from '../blocks/Footer.svelte'
</script>

	<Header logo={{"type":"text","text":"SaaSify","image":{"url":"","alt":""}}} nav_links={[{"link":{"label":"Features","url":"#features"}},{"link":{"label":"Pricing","url":"#pricing"}},{"link":{"label":"About","url":"/about"}},{"link":{"label":"Contact","url":"/contact"}}]} header_cta={{"label":"Get Started","url":"#signup"}} />
	<PageHeader title={"Terms of Service"} subtitle={"Last updated March 2026"} />
	<BasicContent content={"<h2>Agreement to Terms</h2>\n<p>By accessing or using SaaSify, you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not access our services.</p>\n\n<h2>Description of Service</h2>\n<p>SaaSify provides a cloud-based platform for building, deploying, and scaling applications. Features and availability may vary based on your subscription plan.</p>\n\n<h2>Account Terms</h2>\n<ul>\n  <li>You must be 18 years or older to use this service</li>\n  <li>You must provide accurate and complete registration information</li>\n  <li>You are responsible for maintaining the security of your account</li>\n  <li>You are responsible for all activities that occur under your account</li>\n  <li>You must notify us immediately of any unauthorized use</li>\n</ul>\n\n<h2>Acceptable Use</h2>\n<p>You agree not to:</p>\n<ul>\n  <li>Use the service for any illegal purpose</li>\n  <li>Violate any laws in your jurisdiction</li>\n  <li>Attempt to gain unauthorized access to the service</li>\n  <li>Interfere with or disrupt the service</li>\n  <li>Upload malicious code or content</li>\n  <li>Resell or redistribute the service without permission</li>\n</ul>\n\n<h2>Payment Terms</h2>\n<p>Paid plans are billed in advance on a monthly or annual basis. All fees are non-refundable except as required by law or as explicitly stated in these terms. We offer a 30-day money-back guarantee for annual plans.</p>\n\n<h2>Intellectual Property</h2>\n<p>The service and its original content, features, and functionality are owned by SaaSify and are protected by international copyright, trademark, and other intellectual property laws. You retain ownership of any content you create using our platform.</p>\n\n<h2>Limitation of Liability</h2>\n<p>To the maximum extent permitted by law, SaaSify shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the service.</p>\n\n<h2>Service Level Agreement</h2>\n<p>We commit to 99.9% uptime for our Pro and Enterprise plans. Details of our SLA, including credits for downtime, are available in our Service Level Agreement documentation.</p>\n\n<h2>Changes to Terms</h2>\n<p>We reserve the right to modify these terms at any time. We will provide notice of material changes via email or through the service. Continued use after changes constitutes acceptance.</p>\n\n<h2>Contact</h2>\n<p>Questions about these terms should be directed to <a href=\"mailto:legal@saasify.com\">legal@saasify.com</a>.</p>\n"} />
	<Footer logo={{"type":"text","text":"SaaSify","image":{"url":"","alt":""}}} tagline={"The all-in-one platform that helps your team build, deploy, and scale applications without the complexity."} social_links={[{"platform":"twitter","url":"https://twitter.com/saasify"},{"platform":"linkedin","url":"https://linkedin.com/company/saasify"},{"platform":"github","url":"https://github.com/saasify"}]} footer_link_groups={[{"title":"Product","links":[{"link":{"label":"Features","url":"#features"}},{"link":{"label":"Pricing","url":"#pricing"}},{"link":{"label":"Changelog","url":"/changelog"}}]},{"title":"Company","links":[{"link":{"label":"About","url":"/about"}},{"link":{"label":"Blog","url":"/blog"}},{"link":{"label":"Contact","url":"/contact"}}]},{"title":"Legal","links":[{"link":{"label":"Privacy","url":"/privacy"}},{"link":{"label":"Terms","url":"/terms"}}]}]} copyright={"© 2026 SaaSify. All rights reserved."} />
