<div class="section">
  <div class="pala-block-container pala-prose" data-key="content">{@html content}</div>
</div>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pala-css@latest/reset.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pala-css@latest/components.css">

<style>
.section {
  background: white;
  padding: 4rem 0;
  --block-container-max-width: 800px;
}

.pala-prose {
  /* use the :global selector to target elements generated by Markdown fields */
  :global(blockquote) {
    border-left: 0.5rem solid black;
    border-top: 1px solid whitesmoke;
    border-right: 1px solid whitesmoke;
    border-bottom: 1px solid whitesmoke;
  }
}
</style>
